export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="af-magic"
plugins=(git)

if [ -f "$ZSH/oh-my-zsh.sh" ]; then
  source $ZSH/oh-my-zsh.sh
fi

# Aliases
alias vim="nvim"
alias ll="ls -l"
alias update="home-manager switch --flake ~/.config/home-manager#william@laptop"
alias nixflake="cd ~/.config/home-manager && nvim flake.nix"

fastfetch

export PATH=$HOME/.local/bin:$PATH
export EDITOR='nvim'
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent"

#NVM

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# NOTE: Plugin sources are appended by Nix configuration

# Key bindings for history substring search
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

export PATH=/usr/bin:/usr/local/bin:$PATH
